// Paires de mots pour le jeu de l'Imposteur
// Chaque paire contient un mot pour les citoyens et un mot similaire pour l'imposteur

const wordPairs = [
  // Animaux
  { citizen: "Chat", impostor: "Chien" },
  { citizen: "Lion", impostor: "Tigre" },
  { citizen: "Aigle", impostor: "Faucon" },
  { citizen: "Dauphin", impostor: "Requin" },
  { citizen: "Cheval", impostor: "Âne" },
  { citizen: "Papillon", impostor: "Libellule" },
  { citizen: "Grenouille", impostor: "Crapaud" },
  { citizen: "Abeille", impostor: "Guêpe" },
  { citizen: "Loup", impostor: "Renard" },
  { citizen: "Ours", impostor: "Panda" },
  { citizen: "Crocodile", impostor: "Alligator" },
  { citizen: "Pingouin", impostor: "Manchot" },
  { citizen: "Tortue", impostor: "Escargot" },
  { citizen: "Corbeau", impostor: "Pie" },
  { citizen: "Hibou", impostor: "Chouette" },
  { citizen: "Canard", impostor: "Oie" },
  { citizen: "Mouton", impostor: "Chèvre" },
  { citizen: "Lapin", impostor: "Lièvre" },
  { citizen: "Souris", impostor: "Rat" },
  { citizen: "Chameau", impostor: "Dromadaire" },
  { citizen: "Singe", impostor: "Gorille" },
  { citizen: "Cerf", impostor: "Élan" },
  { citizen: "Serpent", impostor: "Lézard" },
  { citizen: "Méduse", impostor: "Pieuvre" },
  { citizen: "Homard", impostor: "Crabe" },

  // Nourriture
  { citizen: "Pizza", impostor: "Hamburger" },
  { citizen: "Croissant", impostor: "Brioche" },
  { citizen: "Pomme", impostor: "Poire" },
  { citizen: "Café", impostor: "Thé" },
  { citizen: "Bière", impostor: "Vin" },
  { citizen: "Chocolat", impostor: "Caramel" },
  { citizen: "Gâteau", impostor: "Tarte" },
  { citizen: "Frites", impostor: "Chips" },
  { citizen: "Spaghetti", impostor: "Lasagne" },
  { citizen: "Glace", impostor: "Sorbet" },
  { citizen: "Fromage", impostor: "Beurre" },
  { citizen: "Pain", impostor: "Baguette" },
  { citizen: "Steak", impostor: "Saucisse" },
  { citizen: "Sushi", impostor: "Maki" },
  { citizen: "Soupe", impostor: "Potage" },
  { citizen: "Salade", impostor: "Crudités" },
  { citizen: "Crêpe", impostor: "Gaufre" },
  { citizen: "Yaourt", impostor: "Crème" },
  { citizen: "Orange", impostor: "Mandarine" },
  { citizen: "Fraise", impostor: "Framboise" },
  { citizen: "Raisin", impostor: "Cerise" },
  { citizen: "Banane", impostor: "Ananas" },
  { citizen: "Miel", impostor: "Confiture" },
  { citizen: "Popcorn", impostor: "Cacahuètes" },
  { citizen: "Bonbon", impostor: "Chewing-gum" },

  // Transports
  { citizen: "Avion", impostor: "Hélicoptère" },
  { citizen: "Vélo", impostor: "Trottinette" },
  { citizen: "Voiture", impostor: "Moto" },
  { citizen: "Train", impostor: "Métro" },
  { citizen: "Bateau", impostor: "Sous-marin" },
  { citizen: "Bus", impostor: "Tramway" },
  { citizen: "Fusée", impostor: "Navette spatiale" },
  { citizen: "Taxi", impostor: "Uber" },
  { citizen: "Camion", impostor: "Fourgon" },
  { citizen: "Jet-ski", impostor: "Bateau à moteur" },
  { citizen: "Parachute", impostor: "Deltaplane" },
  { citizen: "Kayak", impostor: "Canoë" },
  { citizen: "Montgolfière", impostor: "Dirigeable" },
  { citizen: "Skateboard", impostor: "Rollers" },

  // Sports
  { citizen: "Football", impostor: "Rugby" },
  { citizen: "Tennis", impostor: "Badminton" },
  { citizen: "Natation", impostor: "Plongée" },
  { citizen: "Ski", impostor: "Snowboard" },
  { citizen: "Basketball", impostor: "Handball" },
  { citizen: "Boxe", impostor: "Karaté" },
  { citizen: "Golf", impostor: "Mini-golf" },
  { citizen: "Surf", impostor: "Wakeboard" },
  { citizen: "Escalade", impostor: "Alpinisme" },
  { citizen: "Yoga", impostor: "Pilates" },
  { citizen: "Danse", impostor: "Ballet" },
  { citizen: "Escrime", impostor: "Judo" },
  { citizen: "Patinage", impostor: "Hockey" },
  { citizen: "Équitation", impostor: "Polo" },
  { citizen: "Vélo de course", impostor: "VTT" },
  { citizen: "Marathon", impostor: "Sprint" },
  { citizen: "Catch", impostor: "Lutte" },

  // Métiers
  { citizen: "Médecin", impostor: "Infirmier" },
  { citizen: "Avocat", impostor: "Juge" },
  { citizen: "Chef cuisinier", impostor: "Pâtissier" },
  { citizen: "Policier", impostor: "Gendarme" },
  { citizen: "Professeur", impostor: "Moniteur" },
  { citizen: "Architecte", impostor: "Ingénieur" },
  { citizen: "Acteur", impostor: "Comédien" },
  { citizen: "Pilote", impostor: "Steward" },
  { citizen: "Pompier", impostor: "Ambulancier" },
  { citizen: "Boulanger", impostor: "Boucher" },
  { citizen: "Coiffeur", impostor: "Barbier" },
  { citizen: "Photographe", impostor: "Cameraman" },
  { citizen: "Journaliste", impostor: "Présentateur" },
  { citizen: "Dentiste", impostor: "Orthodontiste" },
  { citizen: "Plombier", impostor: "Électricien" },
  { citizen: "Facteur", impostor: "Livreur" },
  { citizen: "DJ", impostor: "Musicien" },

  // Lieux
  { citizen: "Plage", impostor: "Piscine" },
  { citizen: "Montagne", impostor: "Colline" },
  { citizen: "Forêt", impostor: "Jungle" },
  { citizen: "Restaurant", impostor: "Café" },
  { citizen: "Cinéma", impostor: "Théâtre" },
  { citizen: "Hôpital", impostor: "Clinique" },
  { citizen: "École", impostor: "Université" },
  { citizen: "Musée", impostor: "Galerie" },
  { citizen: "Bibliothèque", impostor: "Librairie" },
  { citizen: "Église", impostor: "Cathédrale" },
  { citizen: "Aéroport", impostor: "Gare" },
  { citizen: "Zoo", impostor: "Aquarium" },
  { citizen: "Stade", impostor: "Gymnase" },
  { citizen: "Château", impostor: "Palais" },
  { citizen: "Prison", impostor: "Caserne" },
  { citizen: "Supermarché", impostor: "Épicerie" },
  { citizen: "Discothèque", impostor: "Bar" },
  { citizen: "Parc", impostor: "Jardin" },

  // Objets
  { citizen: "Téléphone", impostor: "Tablette" },
  { citizen: "Livre", impostor: "Magazine" },
  { citizen: "Montre", impostor: "Horloge" },
  { citizen: "Lampe", impostor: "Bougie" },
  { citizen: "Chaise", impostor: "Tabouret" },
  { citizen: "Lit", impostor: "Canapé" },
  { citizen: "Miroir", impostor: "Vitre" },
  { citizen: "Parapluie", impostor: "Parasol" },
  { citizen: "Couteau", impostor: "Ciseaux" },
  { citizen: "Lunettes", impostor: "Jumelles" },
  { citizen: "Clé", impostor: "Serrure" },
  { citizen: "Sac à dos", impostor: "Valise" },
  { citizen: "Balai", impostor: "Aspirateur" },
  { citizen: "Radiateur", impostor: "Climatiseur" },
  { citizen: "Télévision", impostor: "Ordinateur" },
  { citizen: "Stylo", impostor: "Crayon" },
  { citizen: "Fourchette", impostor: "Cuillère" },
  { citizen: "Casserole", impostor: "Poêle" },

  // Musique
  { citizen: "Guitare", impostor: "Ukulélé" },
  { citizen: "Piano", impostor: "Synthétiseur" },
  { citizen: "Violon", impostor: "Violoncelle" },
  { citizen: "Batterie", impostor: "Percussion" },
  { citizen: "Flûte", impostor: "Clarinette" },
  { citizen: "Trompette", impostor: "Saxophone" },
  { citizen: "Harpe", impostor: "Lyre" },
  { citizen: "Accordéon", impostor: "Harmonica" },
  { citizen: "Banjo", impostor: "Mandoline" },

  // Nature
  { citizen: "Soleil", impostor: "Lune" },
  { citizen: "Océan", impostor: "Mer" },
  { citizen: "Volcan", impostor: "Geyser" },
  { citizen: "Rivière", impostor: "Ruisseau" },
  { citizen: "Tempête", impostor: "Ouragan" },
  { citizen: "Neige", impostor: "Grêle" },
  { citizen: "Arc-en-ciel", impostor: "Aurore boréale" },
  { citizen: "Cascade", impostor: "Fontaine" },
  { citizen: "Désert", impostor: "Savane" },
  { citizen: "Glacier", impostor: "Iceberg" },
  { citizen: "Grotte", impostor: "Caverne" },
  { citizen: "Île", impostor: "Presqu'île" },

  // Vêtements
  { citizen: "Chapeau", impostor: "Casquette" },
  { citizen: "Manteau", impostor: "Veste" },
  { citizen: "Pantalon", impostor: "Jean" },
  { citizen: "Chaussures", impostor: "Baskets" },
  { citizen: "Chemise", impostor: "T-shirt" },
  { citizen: "Robe", impostor: "Jupe" },
  { citizen: "Écharpe", impostor: "Foulard" },
  { citizen: "Gants", impostor: "Moufles" },
  { citizen: "Pyjama", impostor: "Robe de chambre" },
  { citizen: "Costume", impostor: "Smoking" },
  { citizen: "Sandales", impostor: "Tongs" },
  { citizen: "Pull", impostor: "Sweat" },

  // Technologie
  { citizen: "Robot", impostor: "Androïde" },
  { citizen: "Drone", impostor: "Hélicoptère RC" },
  { citizen: "Console", impostor: "PC gamer" },
  { citizen: "Casque VR", impostor: "Lunettes 3D" },
  { citizen: "Imprimante", impostor: "Scanner" },
  { citizen: "Clavier", impostor: "Souris" },
  { citizen: "Webcam", impostor: "Caméra" },
  { citizen: "WiFi", impostor: "Bluetooth" },
  { citizen: "Netflix", impostor: "YouTube" },
  { citizen: "Instagram", impostor: "TikTok" },
  { citizen: "Email", impostor: "SMS" },

  // Jeux et divertissement
  { citizen: "Échecs", impostor: "Dames" },
  { citizen: "Poker", impostor: "Blackjack" },
  { citizen: "Monopoly", impostor: "Risk" },
  { citizen: "Puzzle", impostor: "Rubik's Cube" },
  { citizen: "Fléchettes", impostor: "Billard" },
  { citizen: "Karaoké", impostor: "Karting" },
  { citizen: "Bowling", impostor: "Pétanque" },
  { citizen: "Escape game", impostor: "Laser game" },
  { citizen: "Cirque", impostor: "Fête foraine" },
  { citizen: "Concert", impostor: "Festival" },

  // Fêtes et célébrations
  { citizen: "Noël", impostor: "Nouvel An" },
  { citizen: "Halloween", impostor: "Carnaval" },
  { citizen: "Mariage", impostor: "Fiançailles" },
  { citizen: "Anniversaire", impostor: "Fête" },
  { citizen: "Pâques", impostor: "Toussaint" },
  { citizen: "Saint-Valentin", impostor: "Fête des mères" },

  // Fantastique et mythologie
  { citizen: "Dragon", impostor: "Dinosaure" },
  { citizen: "Vampire", impostor: "Loup-garou" },
  { citizen: "Sorcier", impostor: "Magicien" },
  { citizen: "Fantôme", impostor: "Zombie" },
  { citizen: "Sirène", impostor: "Triton" },
  { citizen: "Licorne", impostor: "Pégase" },
  { citizen: "Elfe", impostor: "Nain" },
  { citizen: "Fée", impostor: "Lutin" },
  { citizen: "Ange", impostor: "Démon" },
  { citizen: "Géant", impostor: "Ogre" },

  // Science
  { citizen: "Atome", impostor: "Molécule" },
  { citizen: "Planète", impostor: "Étoile" },
  { citizen: "Microscope", impostor: "Télescope" },
  { citizen: "ADN", impostor: "ARN" },
  { citizen: "Électron", impostor: "Proton" },
  { citizen: "Galaxie", impostor: "Nébuleuse" },
  { citizen: "Trou noir", impostor: "Supernova" },

  // Émotions et états
  { citizen: "Joie", impostor: "Bonheur" },
  { citizen: "Tristesse", impostor: "Mélancolie" },
  { citizen: "Colère", impostor: "Rage" },
  { citizen: "Peur", impostor: "Angoisse" },
  { citizen: "Amour", impostor: "Passion" },
  { citizen: "Fatigue", impostor: "Épuisement" },
  { citizen: "Surprise", impostor: "Choc" },
  { citizen: "Fierté", impostor: "Orgueil" },

  // Opposés et contrastes
  { citizen: "Jour", impostor: "Nuit" },
  { citizen: "Chaud", impostor: "Froid" },
  { citizen: "Noir", impostor: "Blanc" },
  { citizen: "Grand", impostor: "Petit" },
  { citizen: "Haut", impostor: "Bas" },
  { citizen: "Gauche", impostor: "Droite" },
  { citizen: "Avant", impostor: "Arrière" },
  { citizen: "Début", impostor: "Fin" },
  { citizen: "Entrée", impostor: "Sortie" },
  { citizen: "Été", impostor: "Hiver" },
  { citizen: "Printemps", impostor: "Automne" },
  { citizen: "Lever", impostor: "Coucher" },
  { citizen: "Matin", impostor: "Soir" },
  { citizen: "Passé", impostor: "Futur" },
  { citizen: "Ancien", impostor: "Moderne" },
  { citizen: "Vieux", impostor: "Jeune" },
  { citizen: "Rapide", impostor: "Lent" },
  { citizen: "Fort", impostor: "Faible" },
  { citizen: "Riche", impostor: "Pauvre" },
  { citizen: "Plein", impostor: "Vide" },
  { citizen: "Lourd", impostor: "Léger" },
  { citizen: "Dur", impostor: "Mou" },
  { citizen: "Sec", impostor: "Humide" },
  { citizen: "Propre", impostor: "Sale" },
  { citizen: "Calme", impostor: "Agité" },
  { citizen: "Ciel", impostor: "Terre" },
  { citizen: "Nord", impostor: "Sud" },
  { citizen: "Est", impostor: "Ouest" },
  { citizen: "Montée", impostor: "Descente" },
  { citizen: "Question", impostor: "Réponse" },
  { citizen: "Problème", impostor: "Solution" },
  { citizen: "Guerre", impostor: "Paix" },
  { citizen: "Vie", impostor: "Mort" },
  { citizen: "Ombre", impostor: "Lumière" },
  { citizen: "Silence", impostor: "Bruit" },
  { citizen: "Succès", impostor: "Échec" },
  { citizen: "Victoire", impostor: "Défaite" },
  { citizen: "Ami", impostor: "Ennemi" },
  { citizen: "Héros", impostor: "Méchant" },
  { citizen: "Réalité", impostor: "Rêve" },
  { citizen: "Vérité", impostor: "Mensonge" },

  // Couleurs
  { citizen: "Rouge", impostor: "Bleu" },
  { citizen: "Vert", impostor: "Orange" },
  { citizen: "Jaune", impostor: "Violet" },
  { citizen: "Rose", impostor: "Turquoise" },
  { citizen: "Doré", impostor: "Argenté" },
  { citizen: "Beige", impostor: "Marron" },
  { citizen: "Gris", impostor: "Bordeaux" },

  // Super-héros
  { citizen: "Spider-Man", impostor: "Batman" },
  { citizen: "Superman", impostor: "Wonder Woman" },
  { citizen: "Iron Man", impostor: "Captain America" },
  { citizen: "Hulk", impostor: "Thor" },
  { citizen: "Flash", impostor: "Aquaman" },
  { citizen: "Deadpool", impostor: "Wolverine" },
  { citizen: "Black Panther", impostor: "Doctor Strange" },
  { citizen: "Joker", impostor: "Thanos" },

  // Films et séries
  { citizen: "Harry Potter", impostor: "Le Seigneur des Anneaux" },
  { citizen: "Star Wars", impostor: "Star Trek" },
  { citizen: "Titanic", impostor: "Avatar" },
  { citizen: "Game of Thrones", impostor: "Breaking Bad" },
  { citizen: "Friends", impostor: "How I Met Your Mother" },
  { citizen: "Stranger Things", impostor: "The Walking Dead" },
  { citizen: "La Casa de Papel", impostor: "Squid Game" },
  { citizen: "Naruto", impostor: "Dragon Ball" },
  { citizen: "One Piece", impostor: "Demon Slayer" },
  { citizen: "Pokemon", impostor: "Digimon" },
  { citizen: "Minecraft", impostor: "Roblox" },
  { citizen: "Fortnite", impostor: "Call of Duty" },
  { citizen: "FIFA", impostor: "PES" },
  { citizen: "GTA", impostor: "Red Dead Redemption" },
  { citizen: "Mario", impostor: "Sonic" },
  { citizen: "Zelda", impostor: "Skyrim" },

  // Pays et villes
  { citizen: "France", impostor: "Espagne" },
  { citizen: "Italie", impostor: "Grèce" },
  { citizen: "Japon", impostor: "Chine" },
  { citizen: "États-Unis", impostor: "Canada" },
  { citizen: "Brésil", impostor: "Argentine" },
  { citizen: "Allemagne", impostor: "Angleterre" },
  { citizen: "Paris", impostor: "Londres" },
  { citizen: "New York", impostor: "Los Angeles" },
  { citizen: "Tokyo", impostor: "Séoul" },
  { citizen: "Rome", impostor: "Athènes" },
  { citizen: "Dubaï", impostor: "Las Vegas" },

  // Marques et entreprises
  { citizen: "Apple", impostor: "Samsung" },
  { citizen: "Google", impostor: "Microsoft" },
  { citizen: "Amazon", impostor: "Alibaba" },
  { citizen: "Nike", impostor: "Adidas" },
  { citizen: "McDonald's", impostor: "Burger King" },
  { citizen: "Coca-Cola", impostor: "Pepsi" },
  { citizen: "PlayStation", impostor: "Xbox" },
  { citizen: "Ferrari", impostor: "Lamborghini" },
  { citizen: "BMW", impostor: "Mercedes" },
  { citizen: "Rolex", impostor: "Omega" },
  { citizen: "Chanel", impostor: "Dior" },
  { citizen: "Louis Vuitton", impostor: "Gucci" },
  { citizen: "IKEA", impostor: "Conforama" },
  { citizen: "Spotify", impostor: "Deezer" },
  { citizen: "Uber", impostor: "Lyft" },
  { citizen: "Airbnb", impostor: "Booking" },
  { citizen: "WhatsApp", impostor: "Telegram" },
  { citizen: "Facebook", impostor: "Twitter" },
  { citizen: "LinkedIn", impostor: "Indeed" },
  { citizen: "Snapchat", impostor: "BeReal" },

  // Personnages historiques
  { citizen: "Napoléon", impostor: "César" },
  { citizen: "Cléopâtre", impostor: "Marie-Antoinette" },
  { citizen: "Einstein", impostor: "Newton" },
  { citizen: "Léonard de Vinci", impostor: "Michel-Ange" },
  { citizen: "Mozart", impostor: "Beethoven" },
  { citizen: "Van Gogh", impostor: "Picasso" },
  { citizen: "Shakespeare", impostor: "Molière" },

  // Corps humain
  { citizen: "Main", impostor: "Pied" },
  { citizen: "Œil", impostor: "Oreille" },
  { citizen: "Nez", impostor: "Bouche" },
  { citizen: "Bras", impostor: "Jambe" },
  { citizen: "Cœur", impostor: "Cerveau" },
  { citizen: "Dos", impostor: "Ventre" },
  { citizen: "Doigt", impostor: "Orteil" },
  { citizen: "Cheveux", impostor: "Barbe" },
  { citizen: "Dent", impostor: "Langue" },

  // Boissons
  { citizen: "Eau", impostor: "Jus" },
  { citizen: "Limonade", impostor: "Orangina" },
  { citizen: "Champagne", impostor: "Cidre" },
  { citizen: "Whisky", impostor: "Rhum" },
  { citizen: "Vodka", impostor: "Gin" },
  { citizen: "Mojito", impostor: "Piña Colada" },
  { citizen: "Cappuccino", impostor: "Latte" },
  { citizen: "Espresso", impostor: "Americano" },
  { citizen: "Thé vert", impostor: "Thé noir" },
  { citizen: "Smoothie", impostor: "Milkshake" },

  // Métaux et matériaux
  { citizen: "Or", impostor: "Argent" },
  { citizen: "Bronze", impostor: "Cuivre" },
  { citizen: "Fer", impostor: "Acier" },
  { citizen: "Diamant", impostor: "Rubis" },
  { citizen: "Émeraude", impostor: "Saphir" },
  { citizen: "Bois", impostor: "Plastique" },
  { citizen: "Verre", impostor: "Cristal" },
  { citizen: "Coton", impostor: "Soie" },
  { citizen: "Laine", impostor: "Lin" },
  { citizen: "Cuir", impostor: "Daim" },

  // Formes
  { citizen: "Cercle", impostor: "Carré" },
  { citizen: "Triangle", impostor: "Rectangle" },
  { citizen: "Étoile", impostor: "Cœur" },
  { citizen: "Losange", impostor: "Hexagone" },
  { citizen: "Sphère", impostor: "Cube" },
  { citizen: "Pyramide", impostor: "Cône" },

  // Temps et durée
  { citizen: "Seconde", impostor: "Minute" },
  { citizen: "Heure", impostor: "Journée" },
  { citizen: "Semaine", impostor: "Mois" },
  { citizen: "Année", impostor: "Décennie" },
  { citizen: "Siècle", impostor: "Millénaire" },
  { citizen: "Hier", impostor: "Demain" },
  { citizen: "Lundi", impostor: "Vendredi" },
  { citizen: "Janvier", impostor: "Décembre" },

  // Nombres et maths
  { citizen: "Zéro", impostor: "Infini" },
  { citizen: "Premier", impostor: "Dernier" },
  { citizen: "Pair", impostor: "Impair" },
  { citizen: "Plus", impostor: "Moins" },
  { citizen: "Multiplier", impostor: "Diviser" },
  { citizen: "Pourcentage", impostor: "Fraction" },

  // Événements
  { citizen: "Naissance", impostor: "Décès" },
  { citizen: "Départ", impostor: "Arrivée" },
  { citizen: "Ouverture", impostor: "Fermeture" },
  { citizen: "Réveil", impostor: "Endormissement" },
  { citizen: "Création", impostor: "Destruction" },
  { citizen: "Réunion", impostor: "Séparation" },

  // Animaux marins vs terrestres
  { citizen: "Baleine", impostor: "Éléphant" },
  { citizen: "Poisson", impostor: "Oiseau" },
  { citizen: "Requin", impostor: "Lion" },
  { citizen: "Phoque", impostor: "Chien" },

  // Éléments
  { citizen: "Feu", impostor: "Eau" },
  { citizen: "Terre", impostor: "Air" },
  { citizen: "Glace", impostor: "Flamme" },
  { citizen: "Électricité", impostor: "Magnétisme" },

  // Actions opposées
  { citizen: "Courir", impostor: "Marcher" },
  { citizen: "Parler", impostor: "Écouter" },
  { citizen: "Lire", impostor: "Écrire" },
  { citizen: "Donner", impostor: "Recevoir" },
  { citizen: "Acheter", impostor: "Vendre" },
  { citizen: "Construire", impostor: "Démolir" },
  { citizen: "Allumer", impostor: "Éteindre" },
  { citizen: "Ouvrir", impostor: "Fermer" },
  { citizen: "Monter", impostor: "Descendre" },
  { citizen: "Avancer", impostor: "Reculer" },
  { citizen: "Pousser", impostor: "Tirer" },
  { citizen: "Rire", impostor: "Pleurer" },
  { citizen: "Chanter", impostor: "Danser" },
  { citizen: "Dormir", impostor: "Se réveiller" },
  { citizen: "Manger", impostor: "Boire" },

  // Professions créatives
  { citizen: "Écrivain", impostor: "Poète" },
  { citizen: "Sculpteur", impostor: "Peintre" },
  { citizen: "Réalisateur", impostor: "Producteur" },
  { citizen: "Chorégraphe", impostor: "Metteur en scène" },
  { citizen: "Dessinateur", impostor: "Illustrateur" },
  { citizen: "Compositeur", impostor: "Parolier" },

  // Personnages contes
  { citizen: "Cendrillon", impostor: "Blanche-Neige" },
  { citizen: "Le Petit Chaperon Rouge", impostor: "Les Trois Petits Cochons" },
  { citizen: "Peter Pan", impostor: "Pinocchio" },
  { citizen: "La Belle au Bois Dormant", impostor: "La Petite Sirène" },
  { citizen: "Aladin", impostor: "Ali Baba" },
  { citizen: "Le Chat Botté", impostor: "Le Loup" },

  // Desserts et sucreries
  { citizen: "Macaron", impostor: "Éclair" },
  { citizen: "Mille-feuille", impostor: "Paris-Brest" },
  { citizen: "Tiramisu", impostor: "Panna Cotta" },
  { citizen: "Brownie", impostor: "Cookie" },
  { citizen: "Cheesecake", impostor: "Forêt Noire" },
  { citizen: "Profiterole", impostor: "Chou à la crème" },
  { citizen: "Crème brûlée", impostor: "Mousse au chocolat" },

  // Phénomènes météo
  { citizen: "Pluie", impostor: "Brouillard" },
  { citizen: "Orage", impostor: "Éclair" },
  { citizen: "Tonnerre", impostor: "Foudre" },
  { citizen: "Vent", impostor: "Tornade" },
  { citizen: "Canicule", impostor: "Sécheresse" },
  { citizen: "Verglas", impostor: "Gel" },

  // Accessoires
  { citizen: "Bague", impostor: "Bracelet" },
  { citizen: "Collier", impostor: "Pendentif" },
  { citizen: "Boucles d'oreilles", impostor: "Piercing" },
  { citizen: "Cravate", impostor: "Nœud papillon" },
  { citizen: "Ceinture", impostor: "Bretelles" },
  { citizen: "Sac à main", impostor: "Pochette" },

  // Insectes
  { citizen: "Fourmi", impostor: "Termite" },
  { citizen: "Mouche", impostor: "Moustique" },
  { citizen: "Coccinelle", impostor: "Scarabée" },
  { citizen: "Araignée", impostor: "Scorpion" },
  { citizen: "Sauterelle", impostor: "Criquet" },
  { citizen: "Chenille", impostor: "Ver de terre" },

  // ==================== NOUVELLES CATÉGORIES ====================

  // Célébrités Musique
  { citizen: "Beyoncé", impostor: "Rihanna" },
  { citizen: "Michael Jackson", impostor: "Prince" },
  { citizen: "Madonna", impostor: "Lady Gaga" },
  { citizen: "Elvis Presley", impostor: "Johnny Hallyday" },
  { citizen: "The Beatles", impostor: "The Rolling Stones" },
  { citizen: "Bob Marley", impostor: "Bob Dylan" },
  { citizen: "Drake", impostor: "Kanye West" },
  { citizen: "Eminem", impostor: "Jay-Z" },
  { citizen: "Taylor Swift", impostor: "Ariana Grande" },
  { citizen: "Ed Sheeran", impostor: "Bruno Mars" },
  { citizen: "Adele", impostor: "Whitney Houston" },
  { citizen: "Coldplay", impostor: "U2" },
  { citizen: "Daft Punk", impostor: "David Guetta" },
  { citizen: "AC/DC", impostor: "Metallica" },
  { citizen: "Nirvana", impostor: "Guns N' Roses" },
  { citizen: "Queen", impostor: "Led Zeppelin" },
  { citizen: "Pink Floyd", impostor: "The Doors" },
  { citizen: "Shakira", impostor: "Jennifer Lopez" },
  { citizen: "Céline Dion", impostor: "Mariah Carey" },
  { citizen: "Justin Bieber", impostor: "Shawn Mendes" },

  // Célébrités Cinéma
  { citizen: "Leonardo DiCaprio", impostor: "Brad Pitt" },
  { citizen: "Tom Cruise", impostor: "Tom Hanks" },
  { citizen: "Will Smith", impostor: "Denzel Washington" },
  { citizen: "Johnny Depp", impostor: "Robert Downey Jr" },
  { citizen: "Angelina Jolie", impostor: "Jennifer Aniston" },
  { citizen: "Scarlett Johansson", impostor: "Emma Watson" },
  { citizen: "Morgan Freeman", impostor: "Samuel L. Jackson" },
  { citizen: "George Clooney", impostor: "Matt Damon" },
  { citizen: "Robert De Niro", impostor: "Al Pacino" },
  { citizen: "Clint Eastwood", impostor: "Harrison Ford" },
  { citizen: "Jim Carrey", impostor: "Adam Sandler" },
  { citizen: "Dwayne Johnson", impostor: "Vin Diesel" },
  { citizen: "Arnold Schwarzenegger", impostor: "Sylvester Stallone" },
  { citizen: "Bruce Willis", impostor: "Mel Gibson" },
  { citizen: "Jackie Chan", impostor: "Bruce Lee" },
  { citizen: "Jean-Paul Belmondo", impostor: "Alain Delon" },
  { citizen: "Omar Sy", impostor: "Jamel Debbouze" },
  { citizen: "Gérard Depardieu", impostor: "Jean Reno" },
  { citizen: "Marion Cotillard", impostor: "Léa Seydoux" },
  { citizen: "Sophie Marceau", impostor: "Catherine Deneuve" },

  // Sports - Footballeurs
  { citizen: "Messi", impostor: "Ronaldo" },
  { citizen: "Mbappé", impostor: "Haaland" },
  { citizen: "Neymar", impostor: "Vinicius Jr" },
  { citizen: "Zidane", impostor: "Platini" },
  { citizen: "Pelé", impostor: "Maradona" },
  { citizen: "Benzema", impostor: "Griezmann" },
  { citizen: "Pogba", impostor: "Kanté" },
  { citizen: "Modric", impostor: "Kroos" },
  { citizen: "De Bruyne", impostor: "Salah" },
  { citizen: "Lewandowski", impostor: "Suarez" },
  { citizen: "Sergio Ramos", impostor: "Van Dijk" },
  { citizen: "Buffon", impostor: "Neuer" },
  { citizen: "Thierry Henry", impostor: "Didier Drogba" },
  { citizen: "Beckham", impostor: "Ronaldinho" },

  // Sports - Basketteurs
  { citizen: "Michael Jordan", impostor: "LeBron James" },
  { citizen: "Kobe Bryant", impostor: "Shaquille O'Neal" },
  { citizen: "Stephen Curry", impostor: "Kevin Durant" },
  { citizen: "Magic Johnson", impostor: "Larry Bird" },
  { citizen: "Wilt Chamberlain", impostor: "Kareem Abdul-Jabbar" },
  { citizen: "Tony Parker", impostor: "Tim Duncan" },
  { citizen: "Rudy Gobert", impostor: "Victor Wembanyama" },

  // Sports - Tennis
  { citizen: "Federer", impostor: "Nadal" },
  { citizen: "Djokovic", impostor: "Murray" },
  { citizen: "Serena Williams", impostor: "Venus Williams" },
  { citizen: "Agassi", impostor: "Sampras" },
  { citizen: "Borg", impostor: "McEnroe" },

  // Sports - Autres
  { citizen: "Usain Bolt", impostor: "Carl Lewis" },
  { citizen: "Muhammad Ali", impostor: "Mike Tyson" },
  { citizen: "Tiger Woods", impostor: "Phil Mickelson" },
  { citizen: "Michael Phelps", impostor: "Ian Thorpe" },
  { citizen: "Valentino Rossi", impostor: "Marc Marquez" },
  { citizen: "Lewis Hamilton", impostor: "Max Verstappen" },
  { citizen: "Ayrton Senna", impostor: "Alain Prost" },
  { citizen: "Michael Schumacher", impostor: "Sebastian Vettel" },
  { citizen: "Wayne Gretzky", impostor: "Sidney Crosby" },
  { citizen: "Teddy Riner", impostor: "David Douillet" },

  // Équipes sportives
  { citizen: "Real Madrid", impostor: "Barcelone" },
  { citizen: "PSG", impostor: "Marseille" },
  { citizen: "Manchester United", impostor: "Liverpool" },
  { citizen: "Bayern Munich", impostor: "Dortmund" },
  { citizen: "Juventus", impostor: "AC Milan" },
  { citizen: "Lakers", impostor: "Celtics" },
  { citizen: "Bulls", impostor: "Heat" },
  { citizen: "Yankees", impostor: "Red Sox" },
  { citizen: "All Blacks", impostor: "Springboks" },

  // Monuments
  { citizen: "Tour Eiffel", impostor: "Statue de la Liberté" },
  { citizen: "Big Ben", impostor: "Tour de Pise" },
  { citizen: "Colisée", impostor: "Parthénon" },
  { citizen: "Taj Mahal", impostor: "Angkor Wat" },
  { citizen: "Machu Picchu", impostor: "Chichen Itza" },
  { citizen: "Grande Muraille", impostor: "Pyramides d'Égypte" },
  { citizen: "Christ Rédempteur", impostor: "Sphinx" },
  { citizen: "Mont-Saint-Michel", impostor: "Notre-Dame" },
  { citizen: "Opéra de Sydney", impostor: "Capitol" },
  { citizen: "Burj Khalifa", impostor: "Empire State Building" },
  { citizen: "Arc de Triomphe", impostor: "Porte de Brandebourg" },
  { citizen: "Sagrada Familia", impostor: "Cathédrale de Cologne" },
  { citizen: "Château de Versailles", impostor: "Buckingham Palace" },
  { citizen: "Kremlin", impostor: "Maison Blanche" },
  { citizen: "Acropole", impostor: "Forum Romain" },

  // Océans, Mers, Lacs
  { citizen: "Atlantique", impostor: "Pacifique" },
  { citizen: "Méditerranée", impostor: "Mer Rouge" },
  { citizen: "Mer du Nord", impostor: "Mer Baltique" },
  { citizen: "Océan Indien", impostor: "Océan Arctique" },
  { citizen: "Lac Léman", impostor: "Lac de Côme" },
  { citizen: "Lac Victoria", impostor: "Lac Baïkal" },
  { citizen: "Amazone", impostor: "Nil" },
  { citizen: "Mississippi", impostor: "Missouri" },
  { citizen: "Seine", impostor: "Loire" },
  { citizen: "Rhin", impostor: "Danube" },
  { citizen: "Gange", impostor: "Mékong" },

  // Montagnes
  { citizen: "Everest", impostor: "K2" },
  { citizen: "Mont Blanc", impostor: "Cervin" },
  { citizen: "Kilimandjaro", impostor: "Aconcagua" },
  { citizen: "Fuji", impostor: "Etna" },
  { citizen: "Alpes", impostor: "Pyrénées" },
  { citizen: "Rocheuses", impostor: "Andes" },
  { citizen: "Himalaya", impostor: "Atlas" },

  // Continents et régions
  { citizen: "Europe", impostor: "Asie" },
  { citizen: "Afrique", impostor: "Amérique du Sud" },
  { citizen: "Antarctique", impostor: "Arctique" },
  { citizen: "Océanie", impostor: "Amérique du Nord" },
  { citizen: "Moyen-Orient", impostor: "Extrême-Orient" },
  { citizen: "Scandinavie", impostor: "Balkans" },
  { citizen: "Caraïbes", impostor: "Polynésie" },

  // Langues
  { citizen: "Français", impostor: "Espagnol" },
  { citizen: "Anglais", impostor: "Allemand" },
  { citizen: "Chinois", impostor: "Japonais" },
  { citizen: "Arabe", impostor: "Hébreu" },
  { citizen: "Italien", impostor: "Portugais" },
  { citizen: "Russe", impostor: "Polonais" },
  { citizen: "Hindi", impostor: "Bengali" },
  { citizen: "Coréen", impostor: "Vietnamien" },
  { citizen: "Grec", impostor: "Latin" },
  { citizen: "Néerlandais", impostor: "Danois" },

  // Religions
  { citizen: "Christianisme", impostor: "Islam" },
  { citizen: "Bouddhisme", impostor: "Hindouisme" },
  { citizen: "Judaïsme", impostor: "Sikhisme" },
  { citizen: "Catholique", impostor: "Protestant" },
  { citizen: "Église", impostor: "Mosquée" },
  { citizen: "Temple", impostor: "Synagogue" },
  { citizen: "Prêtre", impostor: "Imam" },
  { citizen: "Moine", impostor: "Rabbi" },
  { citizen: "Bible", impostor: "Coran" },
  { citizen: "Torah", impostor: "Véda" },

  // Mythologie grecque
  { citizen: "Zeus", impostor: "Poséidon" },
  { citizen: "Athéna", impostor: "Aphrodite" },
  { citizen: "Apollon", impostor: "Arès" },
  { citizen: "Hadès", impostor: "Hermès" },
  { citizen: "Héra", impostor: "Déméter" },
  { citizen: "Hercule", impostor: "Achille" },
  { citizen: "Ulysse", impostor: "Persée" },
  { citizen: "Minotaure", impostor: "Méduse" },
  { citizen: "Cyclope", impostor: "Centaure" },
  { citizen: "Phoenix", impostor: "Griffon" },

  // Mythologie nordique
  { citizen: "Odin", impostor: "Thor" },
  { citizen: "Loki", impostor: "Freya" },
  { citizen: "Heimdall", impostor: "Baldur" },
  { citizen: "Fenrir", impostor: "Jörmungand" },
  { citizen: "Valkyrie", impostor: "Norne" },
  { citizen: "Asgard", impostor: "Valhalla" },
  { citizen: "Ragnarök", impostor: "Bifröst" },

  // Signes du zodiaque
  { citizen: "Bélier", impostor: "Taureau" },
  { citizen: "Gémeaux", impostor: "Cancer" },
  { citizen: "Lion", impostor: "Vierge" },
  { citizen: "Balance", impostor: "Scorpion" },
  { citizen: "Sagittaire", impostor: "Capricorne" },
  { citizen: "Verseau", impostor: "Poissons" },

  // Planètes
  { citizen: "Mercure", impostor: "Vénus" },
  { citizen: "Mars", impostor: "Jupiter" },
  { citizen: "Saturne", impostor: "Uranus" },
  { citizen: "Neptune", impostor: "Pluton" },
  { citizen: "Terre", impostor: "Lune" },
  { citizen: "Voie Lactée", impostor: "Andromède" },
  { citizen: "Astéroïde", impostor: "Comète" },
  { citizen: "Satellite", impostor: "Météorite" },

  // Univers / Espace
  { citizen: "NASA", impostor: "SpaceX" },
  { citizen: "Astronaute", impostor: "Cosmonaute" },
  { citizen: "Apollo 11", impostor: "Voyager" },
  { citizen: "ISS", impostor: "Hubble" },
  { citizen: "Neil Armstrong", impostor: "Buzz Aldrin" },
  { citizen: "Thomas Pesquet", impostor: "Yuri Gagarine" },

  // Arbres
  { citizen: "Chêne", impostor: "Hêtre" },
  { citizen: "Pin", impostor: "Sapin" },
  { citizen: "Bouleau", impostor: "Peuplier" },
  { citizen: "Olivier", impostor: "Figuier" },
  { citizen: "Palmier", impostor: "Cocotier" },
  { citizen: "Cèdre", impostor: "Séquoia" },
  { citizen: "Érable", impostor: "Platane" },
  { citizen: "Cerisier", impostor: "Pommier" },
  { citizen: "Oranger", impostor: "Citronnier" },
  { citizen: "Bambou", impostor: "Roseau" },

  // Fleurs
  { citizen: "Rose", impostor: "Tulipe" },
  { citizen: "Lys", impostor: "Orchidée" },
  { citizen: "Tournesol", impostor: "Marguerite" },
  { citizen: "Violette", impostor: "Pensée" },
  { citizen: "Lavande", impostor: "Lilas" },
  { citizen: "Jonquille", impostor: "Narcisse" },
  { citizen: "Pivoine", impostor: "Dahlia" },
  { citizen: "Coquelicot", impostor: "Bleuet" },
  { citizen: "Magnolia", impostor: "Camélia" },
  { citizen: "Hibiscus", impostor: "Jasmin" },

  // Fruits exotiques
  { citizen: "Mangue", impostor: "Papaye" },
  { citizen: "Kiwi", impostor: "Fruit de la passion" },
  { citizen: "Litchi", impostor: "Ramboutan" },
  { citizen: "Goyave", impostor: "Grenade" },
  { citizen: "Fruit du dragon", impostor: "Carambole" },
  { citizen: "Noix de coco", impostor: "Avocat" },
  { citizen: "Datte", impostor: "Figue" },

  // Légumes
  { citizen: "Carotte", impostor: "Navet" },
  { citizen: "Tomate", impostor: "Poivron" },
  { citizen: "Courgette", impostor: "Aubergine" },
  { citizen: "Poireau", impostor: "Oignon" },
  { citizen: "Chou", impostor: "Brocoli" },
  { citizen: "Épinard", impostor: "Laitue" },
  { citizen: "Haricot", impostor: "Petit pois" },
  { citizen: "Pomme de terre", impostor: "Patate douce" },
  { citizen: "Artichaut", impostor: "Asperge" },
  { citizen: "Concombre", impostor: "Cornichon" },
  { citizen: "Champignon", impostor: "Truffe" },
  { citizen: "Ail", impostor: "Échalote" },
  { citizen: "Céleri", impostor: "Fenouil" },
  { citizen: "Radis", impostor: "Betterave" },
  { citizen: "Maïs", impostor: "Blé" },

  // Épices et herbes
  { citizen: "Poivre", impostor: "Sel" },
  { citizen: "Cannelle", impostor: "Gingembre" },
  { citizen: "Curcuma", impostor: "Curry" },
  { citizen: "Paprika", impostor: "Piment" },
  { citizen: "Basilic", impostor: "Persil" },
  { citizen: "Thym", impostor: "Romarin" },
  { citizen: "Menthe", impostor: "Coriandre" },
  { citizen: "Safran", impostor: "Cumin" },
  { citizen: "Vanille", impostor: "Anis" },
  { citizen: "Moutarde", impostor: "Wasabi" },

  // Fromages
  { citizen: "Camembert", impostor: "Brie" },
  { citizen: "Roquefort", impostor: "Gorgonzola" },
  { citizen: "Gruyère", impostor: "Emmental" },
  { citizen: "Parmesan", impostor: "Pecorino" },
  { citizen: "Mozzarella", impostor: "Burrata" },
  { citizen: "Chèvre", impostor: "Feta" },
  { citizen: "Comté", impostor: "Beaufort" },
  { citizen: "Reblochon", impostor: "Raclette" },
  { citizen: "Cheddar", impostor: "Gouda" },
  { citizen: "Mascarpone", impostor: "Ricotta" },

  // Plats du monde
  { citizen: "Paella", impostor: "Risotto" },
  { citizen: "Couscous", impostor: "Tajine" },
  { citizen: "Ramen", impostor: "Pho" },
  { citizen: "Tacos", impostor: "Burrito" },
  { citizen: "Pad Thai", impostor: "Nasi Goreng" },
  { citizen: "Moussaka", impostor: "Pastitsio" },
  { citizen: "Fondue", impostor: "Tartiflette" },
  { citizen: "Fish and Chips", impostor: "Shepherd's Pie" },
  { citizen: "Hot Dog", impostor: "Bagel" },
  { citizen: "Kebab", impostor: "Shawarma" },
  { citizen: "Dim Sum", impostor: "Gyoza" },
  { citizen: "Bibimbap", impostor: "Bulgogi" },
  { citizen: "Ceviche", impostor: "Carpaccio" },
  { citizen: "Goulash", impostor: "Bortsch" },
  { citizen: "Currywurst", impostor: "Bratwurst" },
  { citizen: "Falafel", impostor: "Houmous" },
  { citizen: "Churros", impostor: "Beignet" },
  { citizen: "Pretzel", impostor: "Bretzel" },
  { citizen: "Pancake", impostor: "Waffle" },

  // Pâtisseries françaises
  { citizen: "Croissant", impostor: "Pain au chocolat" },
  { citizen: "Baguette", impostor: "Ficelle" },
  { citizen: "Fougasse", impostor: "Focaccia" },
  { citizen: "Madeleine", impostor: "Financier" },
  { citizen: "Cannelé", impostor: "Kouign-amann" },
  { citizen: "Opéra", impostor: "Fraisier" },
  { citizen: "Tarte Tatin", impostor: "Clafoutis" },
  { citizen: "Baba au rhum", impostor: "Savarin" },
  { citizen: "Meringue", impostor: "Religieuse" },

  // Voitures
  { citizen: "Peugeot", impostor: "Renault" },
  { citizen: "Citroën", impostor: "Fiat" },
  { citizen: "Volkswagen", impostor: "Audi" },
  { citizen: "Toyota", impostor: "Honda" },
  { citizen: "Ford", impostor: "Chevrolet" },
  { citizen: "Tesla", impostor: "Rivian" },
  { citizen: "Porsche", impostor: "Maserati" },
  { citizen: "Bugatti", impostor: "McLaren" },
  { citizen: "Rolls-Royce", impostor: "Bentley" },
  { citizen: "Land Rover", impostor: "Jeep" },
  { citizen: "Mini", impostor: "Fiat 500" },
  { citizen: "Mustang", impostor: "Camaro" },
  { citizen: "Golf", impostor: "Clio" },
  { citizen: "SUV", impostor: "Berline" },
  { citizen: "Coupé", impostor: "Cabriolet" },
  { citizen: "Monospace", impostor: "Break" },
  { citizen: "Pick-up", impostor: "4x4" },
  { citizen: "Limousine", impostor: "Van" },

  // Avions et compagnies
  { citizen: "Boeing", impostor: "Airbus" },
  { citizen: "Air France", impostor: "Lufthansa" },
  { citizen: "Emirates", impostor: "Qatar Airways" },
  { citizen: "British Airways", impostor: "KLM" },
  { citizen: "Ryanair", impostor: "EasyJet" },
  { citizen: "First Class", impostor: "Business Class" },
  { citizen: "Low Cost", impostor: "Charter" },

  // Bateaux
  { citizen: "Paquebot", impostor: "Ferry" },
  { citizen: "Yacht", impostor: "Catamaran" },
  { citizen: "Voilier", impostor: "Goélette" },
  { citizen: "Péniche", impostor: "Barge" },
  { citizen: "Porte-avions", impostor: "Destroyer" },
  { citizen: "Titanic", impostor: "Queen Mary" },
  { citizen: "Croisière", impostor: "Traversée" },
  { citizen: "Radeau", impostor: "Pirogue" },

  // Trains
  { citizen: "TGV", impostor: "Eurostar" },
  { citizen: "Shinkansen", impostor: "ICE" },
  { citizen: "Locomotive", impostor: "Wagon" },
  { citizen: "Orient-Express", impostor: "Transsibérien" },
  { citizen: "Tramway", impostor: "Funiculaire" },
  { citizen: "Téléphérique", impostor: "Télésiège" },

  // Technologies
  { citizen: "iPhone", impostor: "Galaxy" },
  { citizen: "MacBook", impostor: "ThinkPad" },
  { citizen: "Windows", impostor: "Mac OS" },
  { citizen: "Android", impostor: "iOS" },
  { citizen: "Chrome", impostor: "Firefox" },
  { citizen: "Gmail", impostor: "Outlook" },
  { citizen: "Word", impostor: "Excel" },
  { citizen: "Photoshop", impostor: "Illustrator" },
  { citizen: "PowerPoint", impostor: "Keynote" },
  { citizen: "Zoom", impostor: "Teams" },
  { citizen: "Slack", impostor: "Discord" },
  { citizen: "GitHub", impostor: "GitLab" },
  { citizen: "AWS", impostor: "Azure" },
  { citizen: "Bitcoin", impostor: "Ethereum" },
  { citizen: "NFT", impostor: "Crypto" },
  { citizen: "ChatGPT", impostor: "Gemini" },
  { citizen: "Siri", impostor: "Alexa" },
  { citizen: "4G", impostor: "5G" },
  { citizen: "Fibre optique", impostor: "ADSL" },
  { citizen: "SSD", impostor: "HDD" },

  // Réseaux sociaux
  { citizen: "Facebook", impostor: "Instagram" },
  { citizen: "Twitter", impostor: "X" },
  { citizen: "TikTok", impostor: "YouTube Shorts" },
  { citizen: "Pinterest", impostor: "Tumblr" },
  { citizen: "Reddit", impostor: "4chan" },
  { citizen: "Twitch", impostor: "Kick" },
  { citizen: "OnlyFans", impostor: "Patreon" },
  { citizen: "WhatsApp", impostor: "Signal" },
  { citizen: "Messenger", impostor: "iMessage" },
  { citizen: "Tinder", impostor: "Bumble" },

  // Jeux vidéo - Séries
  { citizen: "Assassin's Creed", impostor: "Prince of Persia" },
  { citizen: "Final Fantasy", impostor: "Dragon Quest" },
  { citizen: "The Witcher", impostor: "Elder Scrolls" },
  { citizen: "Dark Souls", impostor: "Elden Ring" },
  { citizen: "God of War", impostor: "Devil May Cry" },
  { citizen: "Uncharted", impostor: "Tomb Raider" },
  { citizen: "Resident Evil", impostor: "Silent Hill" },
  { citizen: "Metal Gear Solid", impostor: "Splinter Cell" },
  { citizen: "Need for Speed", impostor: "Forza" },
  { citizen: "Gran Turismo", impostor: "F1" },
  { citizen: "The Sims", impostor: "Animal Crossing" },
  { citizen: "Civilization", impostor: "Age of Empires" },
  { citizen: "League of Legends", impostor: "Dota 2" },
  { citizen: "Counter-Strike", impostor: "Valorant" },
  { citizen: "Overwatch", impostor: "Apex Legends" },
  { citizen: "World of Warcraft", impostor: "Guild Wars" },
  { citizen: "Diablo", impostor: "Path of Exile" },
  { citizen: "Halo", impostor: "Destiny" },
  { citizen: "Battlefield", impostor: "Call of Duty" },
  { citizen: "Among Us", impostor: "Fall Guys" },
  { citizen: "Stardew Valley", impostor: "Harvest Moon" },
  { citizen: "Tetris", impostor: "Candy Crush" },

  // Consoles
  { citizen: "PlayStation 5", impostor: "Xbox Series X" },
  { citizen: "Nintendo Switch", impostor: "Steam Deck" },
  { citizen: "Game Boy", impostor: "PSP" },
  { citizen: "Super Nintendo", impostor: "Mega Drive" },
  { citizen: "Atari", impostor: "Commodore" },
  { citizen: "Wii", impostor: "Kinect" },
  { citizen: "VR Quest", impostor: "PlayStation VR" },

  // Personnages de jeux
  { citizen: "Link", impostor: "Zelda" },
  { citizen: "Luigi", impostor: "Wario" },
  { citizen: "Peach", impostor: "Daisy" },
  { citizen: "Pikachu", impostor: "Dracaufeu" },
  { citizen: "Kratos", impostor: "Dante" },
  { citizen: "Lara Croft", impostor: "Nathan Drake" },
  { citizen: "Master Chief", impostor: "Doom Guy" },
  { citizen: "Cloud", impostor: "Sephiroth" },
  { citizen: "Solid Snake", impostor: "Sam Fisher" },
  { citizen: "Geralt", impostor: "Ciri" },
  { citizen: "Pac-Man", impostor: "Bomberman" },
  { citizen: "Donkey Kong", impostor: "Diddy Kong" },
  { citizen: "Kirby", impostor: "Yoshi" },
  { citizen: "Samus", impostor: "Captain Falcon" },

  // Animés - Personnages
  { citizen: "Goku", impostor: "Vegeta" },
  { citizen: "Naruto", impostor: "Sasuke" },
  { citizen: "Luffy", impostor: "Zoro" },
  { citizen: "Eren", impostor: "Mikasa" },
  { citizen: "Light Yagami", impostor: "L" },
  { citizen: "Edward Elric", impostor: "Alphonse Elric" },
  { citizen: "Ichigo", impostor: "Rukia" },
  { citizen: "Saitama", impostor: "Genos" },
  { citizen: "Tanjiro", impostor: "Nezuko" },
  { citizen: "Gon", impostor: "Killua" },
  { citizen: "Ash Ketchum", impostor: "Sacha" },
  { citizen: "Totoro", impostor: "Chihiro" },
  { citizen: "Sailor Moon", impostor: "Sakura" },
  { citizen: "Son Gohan", impostor: "Piccolo" },
  { citizen: "Frieza", impostor: "Cell" },

  // Animés - Séries
  { citizen: "Death Note", impostor: "Code Geass" },
  { citizen: "Attack on Titan", impostor: "Demon Slayer" },
  { citizen: "Fullmetal Alchemist", impostor: "Hunter x Hunter" },
  { citizen: "My Hero Academia", impostor: "Jujutsu Kaisen" },
  { citizen: "One Punch Man", impostor: "Mob Psycho 100" },
  { citizen: "Evangelion", impostor: "Gundam" },
  { citizen: "Cowboy Bebop", impostor: "Samurai Champloo" },
  { citizen: "Studio Ghibli", impostor: "Makoto Shinkai" },
  { citizen: "Your Name", impostor: "Weathering with You" },
  { citizen: "Spirited Away", impostor: "Howl's Moving Castle" },

  // Disney / Pixar
  { citizen: "Mickey", impostor: "Donald" },
  { citizen: "Simba", impostor: "Mufasa" },
  { citizen: "Elsa", impostor: "Anna" },
  { citizen: "Raiponce", impostor: "Vaiana" },
  { citizen: "Woody", impostor: "Buzz" },
  { citizen: "Nemo", impostor: "Dory" },
  { citizen: "Mike Wazowski", impostor: "Sully" },
  { citizen: "Wall-E", impostor: "Eve" },
  { citizen: "Rémy", impostor: "Linguini" },
  { citizen: "Lightning McQueen", impostor: "Mater" },
  { citizen: "Olaf", impostor: "Marshmallow" },
  { citizen: "Maléfique", impostor: "Cruella" },
  { citizen: "Scar", impostor: "Jafar" },
  { citizen: "Ursula", impostor: "La Reine de Cœur" },
  { citizen: "Stitch", impostor: "Baymax" },

  // Harry Potter
  { citizen: "Harry", impostor: "Ron" },
  { citizen: "Hermione", impostor: "Ginny" },
  { citizen: "Dumbledore", impostor: "Gandalf" },
  { citizen: "Voldemort", impostor: "Sauron" },
  { citizen: "Snape", impostor: "Draco" },
  { citizen: "Gryffondor", impostor: "Serpentard" },
  { citizen: "Serdaigle", impostor: "Poufsouffle" },
  { citizen: "Poudlard", impostor: "Mordor" },
  { citizen: "Quidditch", impostor: "Ping-pong" },
  { citizen: "Baguette magique", impostor: "Épée" },

  // Le Seigneur des Anneaux
  { citizen: "Frodon", impostor: "Sam" },
  { citizen: "Aragorn", impostor: "Legolas" },
  { citizen: "Gimli", impostor: "Boromir" },
  { citizen: "Gandalf le Gris", impostor: "Gandalf le Blanc" },
  { citizen: "Gollum", impostor: "Sméagol" },
  { citizen: "Bilbo", impostor: "Frodon" },
  { citizen: "Mordor", impostor: "Isengard" },
  { citizen: "Minas Tirith", impostor: "Helms Deep" },
  { citizen: "Anneau Unique", impostor: "Palantír" },
  { citizen: "Orque", impostor: "Gobelin" },
  { citizen: "Balrog", impostor: "Nazgûl" },

  // Star Wars
  { citizen: "Luke Skywalker", impostor: "Anakin Skywalker" },
  { citizen: "Dark Vador", impostor: "Palpatine" },
  { citizen: "Han Solo", impostor: "Chewbacca" },
  { citizen: "Leia", impostor: "Padmé" },
  { citizen: "Yoda", impostor: "Obi-Wan" },
  { citizen: "R2-D2", impostor: "C-3PO" },
  { citizen: "BB-8", impostor: "D-O" },
  { citizen: "Boba Fett", impostor: "Jango Fett" },
  { citizen: "Kylo Ren", impostor: "Rey" },
  { citizen: "Mandalorien", impostor: "Stormtrooper" },
  { citizen: "Jedi", impostor: "Sith" },
  { citizen: "Sabre laser", impostor: "Blaster" },
  { citizen: "Millennium Falcon", impostor: "X-Wing" },
  { citizen: "Étoile de la Mort", impostor: "Death Star" },
  { citizen: "Tatooine", impostor: "Naboo" },

  // Marvel
  { citizen: "Avengers", impostor: "X-Men" },
  { citizen: "Scarlet Witch", impostor: "Jean Grey" },
  { citizen: "Black Widow", impostor: "Catwoman" },
  { citizen: "Hawkeye", impostor: "Green Arrow" },
  { citizen: "Gamora", impostor: "Nebula" },
  { citizen: "Star-Lord", impostor: "Rocket" },
  { citizen: "Groot", impostor: "Drax" },
  { citizen: "Vision", impostor: "Ultron" },
  { citizen: "Ant-Man", impostor: "Wasp" },
  { citizen: "Loki", impostor: "Thor" },
  { citizen: "Thanos", impostor: "Galactus" },
  { citizen: "Nick Fury", impostor: "Maria Hill" },
  { citizen: "Infinity Stones", impostor: "Tesseract" },
  { citizen: "Asgard", impostor: "Wakanda" },

  // DC Comics
  { citizen: "Justice League", impostor: "Teen Titans" },
  { citizen: "Alfred", impostor: "Robin" },
  { citizen: "Catwoman", impostor: "Harley Quinn" },
  { citizen: "Bane", impostor: "Penguin" },
  { citizen: "Lex Luthor", impostor: "Brainiac" },
  { citizen: "Green Lantern", impostor: "Martian Manhunter" },
  { citizen: "Cyborg", impostor: "Raven" },
  { citizen: "Batmobile", impostor: "Batwing" },
  { citizen: "Gotham", impostor: "Metropolis" },
  { citizen: "Arkham", impostor: "Belle Reve" },
  { citizen: "Kryptonite", impostor: "Batarang" },

  // Livres classiques
  { citizen: "Les Misérables", impostor: "Notre-Dame de Paris" },
  { citizen: "Le Petit Prince", impostor: "Le Petit Nicolas" },
  { citizen: "Guerre et Paix", impostor: "Crime et Châtiment" },
  { citizen: "Don Quichotte", impostor: "Les Trois Mousquetaires" },
  { citizen: "Oliver Twist", impostor: "David Copperfield" },
  { citizen: "Dracula", impostor: "Frankenstein" },
  { citizen: "Sherlock Holmes", impostor: "Hercule Poirot" },
  { citizen: "Le Comte de Monte-Cristo", impostor: "Le Bossu de Notre-Dame" },
  { citizen: "L'Odyssée", impostor: "L'Iliade" },
  { citizen: "Roméo et Juliette", impostor: "Hamlet" },
  { citizen: "1984", impostor: "Le Meilleur des Mondes" },
  { citizen: "Fahrenheit 451", impostor: "La Ferme des Animaux" },
  { citizen: "Moby Dick", impostor: "Vingt Mille Lieues sous les Mers" },
  { citizen: "Alice au Pays des Merveilles", impostor: "Le Magicien d'Oz" },
  { citizen: "Charlie et la Chocolaterie", impostor: "Matilda" },

  // Auteurs
  { citizen: "Victor Hugo", impostor: "Alexandre Dumas" },
  { citizen: "Molière", impostor: "Racine" },
  { citizen: "Voltaire", impostor: "Rousseau" },
  { citizen: "Balzac", impostor: "Zola" },
  { citizen: "Flaubert", impostor: "Maupassant" },
  { citizen: "Camus", impostor: "Sartre" },
  { citizen: "Proust", impostor: "Gide" },
  { citizen: "J.K. Rowling", impostor: "J.R.R. Tolkien" },
  { citizen: "Stephen King", impostor: "Dean Koontz" },
  { citizen: "Agatha Christie", impostor: "Arthur Conan Doyle" },
  { citizen: "George Orwell", impostor: "Aldous Huxley" },
  { citizen: "Isaac Asimov", impostor: "Philip K. Dick" },
  { citizen: "Jules Verne", impostor: "H.G. Wells" },
  { citizen: "Edgar Allan Poe", impostor: "H.P. Lovecraft" },
  { citizen: "Ernest Hemingway", impostor: "F. Scott Fitzgerald" },

  // Peintres
  { citizen: "Monet", impostor: "Manet" },
  { citizen: "Renoir", impostor: "Degas" },
  { citizen: "Cézanne", impostor: "Gauguin" },
  { citizen: "Rembrandt", impostor: "Vermeer" },
  { citizen: "Raphaël", impostor: "Le Caravage" },
  { citizen: "Dali", impostor: "Magritte" },
  { citizen: "Warhol", impostor: "Lichtenstein" },
  { citizen: "Mondrian", impostor: "Kandinsky" },
  { citizen: "Klimt", impostor: "Schiele" },
  { citizen: "Frida Kahlo", impostor: "Diego Rivera" },
  { citizen: "Banksy", impostor: "JR" },
  { citizen: "Basquiat", impostor: "Keith Haring" },

  // Instruments de musique (suite)
  { citizen: "Contrebasse", impostor: "Violoncelle" },
  { citizen: "Trombone", impostor: "Cor" },
  { citizen: "Hautbois", impostor: "Basson" },
  { citizen: "Xylophone", impostor: "Marimba" },
  { citizen: "Djembé", impostor: "Bongo" },
  { citizen: "Orgue", impostor: "Clavecin" },
  { citizen: "Cornemuse", impostor: "Accordéon" },
  { citizen: "Sitar", impostor: "Oud" },
  { citizen: "Didgeridoo", impostor: "Shakuhachi" },
  { citizen: "Steel Drum", impostor: "Handpan" },

  // Genres musicaux
  { citizen: "Rock", impostor: "Pop" },
  { citizen: "Jazz", impostor: "Blues" },
  { citizen: "Rap", impostor: "Hip-Hop" },
  { citizen: "Reggae", impostor: "Ska" },
  { citizen: "Metal", impostor: "Punk" },
  { citizen: "Électro", impostor: "Techno" },
  { citizen: "House", impostor: "Trance" },
  { citizen: "Soul", impostor: "R&B" },
  { citizen: "Country", impostor: "Folk" },
  { citizen: "Classique", impostor: "Baroque" },
  { citizen: "Opéra", impostor: "Comédie musicale" },
  { citizen: "Gospel", impostor: "Chorale" },
  { citizen: "Disco", impostor: "Funk" },
  { citizen: "Salsa", impostor: "Bachata" },
  { citizen: "Flamenco", impostor: "Tango" },
  { citizen: "K-Pop", impostor: "J-Pop" },



  // Films cultes
  { citizen: "Pulp Fiction", impostor: "Kill Bill" },
  { citizen: "Inception", impostor: "Interstellar" },
  { citizen: "The Matrix", impostor: "Blade Runner" },
  { citizen: "Fight Club", impostor: "American History X" },
  { citizen: "Forrest Gump", impostor: "Rain Man" },
  { citizen: "The Godfather", impostor: "Scarface" },
  { citizen: "Shawshank Redemption", impostor: "Green Mile" },
  { citizen: "Gladiator", impostor: "Braveheart" },
  { citizen: "Jurassic Park", impostor: "King Kong" },
  { citizen: "E.T.", impostor: "Close Encounters" },
  { citizen: "Back to the Future", impostor: "Terminator" },
  { citizen: "The Lion King", impostor: "Bambi" },
  { citizen: "Shrek", impostor: "Monsters, Inc." },
  { citizen: "Finding Nemo", impostor: "Shark Tale" },
  { citizen: "Frozen", impostor: "Tangled" },
  { citizen: "Coco", impostor: "Book of Life" },
  { citizen: "Despicable Me", impostor: "Megamind" },
  { citizen: "Zootopia", impostor: "Sing" },
  { citizen: "Encanto", impostor: "Luca" },
  { citizen: "Moana", impostor: "Raya" },



  // Stands-up / Humoristes
  { citizen: "Gad Elmaleh", impostor: "Jamel Debbouze" },
  { citizen: "Florence Foresti", impostor: "Muriel Robin" },
  { citizen: "Coluche", impostor: "Desproges" },
  { citizen: "Raymond Devos", impostor: "Fernand Raynaud" },
  { citizen: "Les Inconnus", impostor: "Les Nuls" },
  { citizen: "Kev Adams", impostor: "Les Bodin's" },
  { citizen: "Eddie Murphy", impostor: "Chris Rock" },
  { citizen: "Dave Chappelle", impostor: "Kevin Hart" },
  { citizen: "Jerry Seinfeld", impostor: "Larry David" },
  { citizen: "Ricky Gervais", impostor: "Rowan Atkinson" },
  { citizen: "Charlie Chaplin", impostor: "Buster Keaton" },
  { citizen: "Louis de Funès", impostor: "Bourvil" },
  { citizen: "Jean Dujardin", impostor: "Guillaume Canet" },
  { citizen: "Pierre Richard", impostor: "Gérard Jugnot" },



  // Professions médicales
  { citizen: "Chirurgien", impostor: "Anesthésiste" },
  { citizen: "Cardiologue", impostor: "Pneumologue" },
  { citizen: "Dermatologue", impostor: "Allergologue" },
  { citizen: "Ophtalmologue", impostor: "ORL" },
  { citizen: "Pédiatre", impostor: "Gériatre" },
  { citizen: "Psychiatre", impostor: "Psychologue" },
  { citizen: "Kinésithérapeute", impostor: "Ostéopathe" },
  { citizen: "Sage-femme", impostor: "Gynécologue" },
  { citizen: "Radiologue", impostor: "Échographiste" },
  { citizen: "Ambulancier", impostor: "Brancardier" },
  { citizen: "Pharmacien", impostor: "Laborantin" },
  { citizen: "Vétérinaire", impostor: "Zoologue" },

  // Justice
  { citizen: "Procureur", impostor: "Avocat" },
  { citizen: "Magistrat", impostor: "Greffier" },
  { citizen: "Huissier", impostor: "Notaire" },
  { citizen: "Président du tribunal", impostor: "Jury" },
  { citizen: "Accusé", impostor: "Témoin" },
  { citizen: "Coupable", impostor: "Innocent" },
  { citizen: "Acquittement", impostor: "Condamnation" },
  { citizen: "Prison", impostor: "Liberté conditionnelle" },

  // Militaire
  { citizen: "Général", impostor: "Colonel" },
  { citizen: "Capitaine", impostor: "Lieutenant" },
  { citizen: "Sergent", impostor: "Caporal" },
  { citizen: "Soldat", impostor: "Recrue" },
  { citizen: "Armée de terre", impostor: "Marine" },
  { citizen: "Armée de l'air", impostor: "Parachutiste" },
  { citizen: "Légionnaire", impostor: "Commando" },
  { citizen: "Infanterie", impostor: "Cavalerie" },
  { citizen: "Artillerie", impostor: "Génie" },
  { citizen: "Tank", impostor: "Hélicoptère de combat" },
  { citizen: "Porte-avions", impostor: "Sous-marin nucléaire" },
  { citizen: "Chasseur", impostor: "Bombardier" },
  { citizen: "Missile", impostor: "Drone de combat" },
  { citizen: "Grenade", impostor: "Mine" },
  { citizen: "Fusil", impostor: "Mitrailleuse" },
  { citizen: "Pistolet", impostor: "Revolver" },
  { citizen: "Arc", impostor: "Arbalète" },
  { citizen: "Épée", impostor: "Lance" },
  { citizen: "Bouclier", impostor: "Armure" },
  { citizen: "Casque", impostor: "Gilet pare-balles" },

  // Cartes à jouer
  { citizen: "As", impostor: "Roi" },
  { citizen: "Dame", impostor: "Valet" },
  { citizen: "Cœur", impostor: "Carreau" },
  { citizen: "Pique", impostor: "Trèfle" },
  { citizen: "Joker", impostor: "Atout" },
  { citizen: "Belote", impostor: "Tarot" },
  { citizen: "Bridge", impostor: "Rami" },
  { citizen: "Uno", impostor: "Skip-Bo" },

  // Jeux de société
  { citizen: "Scrabble", impostor: "Boggle" },
  { citizen: "Cluedo", impostor: "Mysterium" },
  { citizen: "Trivial Pursuit", impostor: "Timeline" },
  { citizen: "Pictionary", impostor: "Dessine c'est gagné" },
  { citizen: "Taboo", impostor: "Time's Up" },
  { citizen: "Dixit", impostor: "Codenames" },
  { citizen: "Catane", impostor: "Carcassonne" },
  { citizen: "7 Wonders", impostor: "Splendor" },
  { citizen: "Azul", impostor: "Patchwork" },
  { citizen: "Pandemic", impostor: "Zombicide" },
  { citizen: "Loup-Garou", impostor: "Mafia" },
  { citizen: "Secret Hitler", impostor: "The Resistance" },
  { citizen: "Jungle Speed", impostor: "Dobble" },
  { citizen: "Jenga", impostor: "Mikado" },
  { citizen: "Puissance 4", impostor: "Morpion" },
  { citizen: "Bataille navale", impostor: "Stratego" },
  { citizen: "Backgammon", impostor: "Go" },
  { citizen: "Mah-jong", impostor: "Dominos" }
];

/**
 * Retourne une paire de mots aléatoire
 * @returns {{ citizen: string, impostor: string }}
 */
function getRandomWordPair() {
  const index = Math.floor(Math.random() * wordPairs.length);
  return wordPairs[index];
}

/**
 * Retourne toutes les paires de mots
 * @returns {Array<{ citizen: string, impostor: string }>}
 */
function getAllWordPairs() {
  return wordPairs;
}

module.exports = {
  getRandomWordPair,
  getAllWordPairs,
  wordPairs
};
