// Catégorie Maison & Objets : Mobilier, Outils, Vêtements, Pièces
module.exports = [
	// Mobilier et Pièces
	{ citizen: "Chaise", impostor: "Tabouret" },
	{ citizen: "Table", impostor: "Bureau" },
	{ citizen: "Canapé", impostor: "Fauteuil" },
	{ citizen: "Lit", impostor: "Hamac" },
	{ citizen: "Armoire", impostor: "Commode" },
	{ citizen: "Lampe", impostor: "Bougie" },
	{ citizen: "Tapis", impostor: "Moquette" },
	{ citizen: "Rideau", impostor: "Store" },
	{ citizen: "Porte", impostor: "Fenêtre" },
	{ citizen: "Sol", impostor: "Plafond" },
	{ citizen: "Mur", impostor: "Toit" },
	{ citizen: "Cuisine", impostor: "Salon" },
	{ citizen: "Chambre", impostor: "Salle de bain" },
	{ citizen: "Garage", impostor: "Grenier" },
	{ citizen: "Escalier", impostor: "Ascenseur" },
	{ citizen: "Balcon", impostor: "Terrasse" },
	{ citizen: "Jardin", impostor: "Cour" },

	// Objets du quotidien
	{ citizen: "Couteau", impostor: "Fourchette" },
	{ citizen: "Cuillère", impostor: "Louche" },
	{ citizen: "Assiette", impostor: "Bol" },
	{ citizen: "Verre", impostor: "Tasse" },
	{ citizen: "Brosse à dents", impostor: "Dentifrice" },
	{ citizen: "Savon", impostor: "Shampoing" },
	{ citizen: "Serviette", impostor: "Torchon" },
	{ citizen: "Balai", impostor: "Aspirateur" },
	{ citizen: "Éponge", impostor: "Chiffon" },
	{ citizen: "Stylo", impostor: "Crayon" },
	{ citizen: "Livre", impostor: "Cahier" },
	{ citizen: "Téléphone", impostor: "Tablette" },
	{ citizen: "Ordinateur", impostor: "Télévision" },
	{ citizen: "Montre", impostor: "Réveil" },
	{ citizen: "Clé", impostor: "Carte" },
	{ citizen: "Sac", impostor: "Valise" },
	{ citizen: "Parapluie", impostor: "Imperméable" },
	{ citizen: "Lunettes", impostor: "Lentilles" },

	// Vêtements
	{ citizen: "Pantalon", impostor: "Short" },
	{ citizen: "Chemise", impostor: "T-shirt" },
	{ citizen: "Pull", impostor: "Sweat" },
	{ citizen: "Manteau", impostor: "Veste" },
	{ citizen: "Chaussettes", impostor: "Collants" },
	{ citizen: "Chaussures", impostor: "Bottes" },
	{ citizen: "Chapeau", impostor: "Casquette" },
	{ citizen: "Écharpe", impostor: "Foulard" },
	{ citizen: "Gants", impostor: "Moufles" },
	{ citizen: "Pyjama", impostor: "Peignoir" },
	{ citizen: "Robe", impostor: "Jupe" },
	{ citizen: "Ceinture", impostor: "Bretelles" },
	{ citizen: "Bijou", impostor: "Montre" }
];
